#!/bin/bash
# $1 is the first CLI argument, this is used as a prefix for installation by package managers i.e. portage, where there is a sandbox
# In portage's case $1 needs to be equal to $ED for it to be correctly installed, it will later be merged correctly
registryDir=$(./setup-xdg-global "$1")
cp xinitrc "$registryDir" # Copy the xinitrc file to this directory so that it can be run as the default X11 startup script
cp Xft.xrdb "$registryDir" # Copy the fallback Xft.xrdb file to the registry

# Copy files to /usr/bin
cp ude-setup-user-dirs ude-setup-xdg-global "$1"/usr/bin
